services:
  zealot:
    build: .
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - ZEALOT_DATABASE_URL=${ZEALOT_DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - BIND_ON=${BIND_ON}
      # SSO 配置
      - SSO_BASE_URL=${SSO_BASE_URL}
      - SSO_BACKEND_ID=${SSO_BACKEND_ID}
    volumes:
      - zealot_data:/app/data
    restart: unless-stopped
    ports:
      - "3063:3063"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  zealot_data:
  postgres_data:
  redis_data: