name: Clean Unused Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # every day
jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old unused images
    steps:
      - name: Clean tryzealot/zealot images
        uses: actions/delete-package-versions@v5
        with:
          package-name: zealot
          package-type: container
          token: ${{ secrets.SECRET_API_TOKEN }}
          delete-only-untagged-versions: 'true'
      - name: Clean tryzealot/codespace images
        uses: actions/delete-package-versions@v5
        with:
          package-name: codespace
          package-type: container
          token: ${{ secrets.SECRET_API_TOKEN }}
          delete-only-untagged-versions: 'true'
